'use client';

import React from 'react';
import Link from 'next/link';
import { Fish, Database, Shield, Image, BookOpen, ChevronLeft, Sparkles } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function AssistantAboutPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="flex-1 pt-16">
        <div className="max-w-3xl mx-auto px-4 py-12">
          <Link href="/assistant" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
            <ChevronLeft size={16} />
            Back to Assistant
          </Link>

          {/* Hero */}
          <div className="flex items-center gap-4 mb-8">
            <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary to-ocean-600 flex items-center justify-center">
              <Sparkles size={24} className="text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-foreground">About the Seafood Vision Assistant</h1>
              <p className="text-muted-foreground text-sm mt-1">AI-assisted answers. Real seafood knowledge. Real seafood imagery.</p>
            </div>
          </div>

          {/* Core principles */}
          <div className="space-y-6">
            <section className="bg-card border border-border rounded-2xl p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Database size={16} className="text-primary" />
                </div>
                <h2 className="text-base font-semibold text-foreground">Built on Seafood Vision data</h2>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                The assistant draws exclusively from the Seafood Vision knowledge base — verified species records, commercial products, packaging configurations, certifications, markets, and public documents. It does not search the internet or use general AI knowledge.
              </p>
            </section>

            <section className="bg-card border border-border rounded-2xl p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Shield size={16} className="text-primary" />
                </div>
                <h2 className="text-base font-semibold text-foreground">Verified information only</h2>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed mb-3">
                Responses are built from data with verified or public status. The assistant clearly indicates when information is limited, under review, or unavailable. It will never invent a species, certification, origin, price, or source.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {[
                  { label: 'High confidence', desc: 'Multiple verified sources', color: 'bg-emerald-50 border-emerald-200 text-emerald-700' },
                  { label: 'Moderate confidence', desc: 'Some verified data', color: 'bg-amber-50 border-amber-200 text-amber-700' },
                  { label: 'Limited information', desc: 'Insufficient verified data', color: 'bg-orange-50 border-orange-200 text-orange-700' },
                ]?.map((c) => (
                  <div key={c?.label} className={`p-3 rounded-xl border text-xs ${c?.color}`}>
                    <p className="font-semibold">{c?.label}</p>
                    <p className="opacity-80 mt-0.5">{c?.desc}</p>
                  </div>
                ))}
              </div>
            </section>

            <section className="bg-card border border-border rounded-2xl p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Image size={16} className="text-primary" />
                </div>
                <h2 className="text-base font-semibold text-foreground">Real seafood imagery</h2>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                All images in Seafood Vision are real photographs of actual seafood products, species, and packaging. The assistant may reference these images, but they are never AI-generated. Using AI to assist with answers does not mean the photos are generated by AI.
              </p>
            </section>

            <section className="bg-card border border-border rounded-2xl p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
                  <BookOpen size={16} className="text-primary" />
                </div>
                <h2 className="text-base font-semibold text-foreground">Not a certification authority</h2>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                The assistant is a professional reference tool. It is not a certification body, regulatory authority, or legal advisor. For compliance, food safety, import/export regulations, or certification requirements, always verify with the relevant authority.
              </p>
            </section>

            <section className="bg-card border border-border rounded-2xl p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Fish size={16} className="text-primary" />
                </div>
                <h2 className="text-base font-semibold text-foreground">What the assistant can help with</h2>
              </div>
              <ul className="space-y-2 text-sm text-muted-foreground">
                {[
                  'Identifying species by common or scientific name',
                  'Finding verified commercial product forms',
                  'Exploring packaging configurations',
                  'Discovering referenced certifications',
                  'Finding public technical documents',
                  'Searching real seafood photos',
                  'Comparing product forms or species',
                  'Exploring market references',
                ]?.map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            </section>
          </div>

          <div className="mt-8 flex items-center justify-between">
            <Link href="/assistant/disclaimer" className="text-sm text-muted-foreground hover:text-foreground transition-colors underline">
              Read full disclaimer
            </Link>
            <Link href="/assistant" className="btn-primary text-sm">
              Start asking
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
