import React from 'react';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Fish, Camera, Globe as Globe2, ShieldCheck } from 'lucide-react';
import Icon from '@/components/ui/AppIcon';


export default function AboutPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="max-w-screen-2xl mx-auto px-4 lg:px-8 xl:px-10 2xl:px-16 pt-24 pb-16">
        {/* Hero */}
        <div className="max-w-3xl mb-16">
          <p className="text-xs font-semibold uppercase tracking-widest text-secondary mb-3">About</p>
          <h1 className="text-4xl font-bold text-foreground mb-5 leading-tight">
            Real Seafood. Real Images.<br />Trusted Worldwide.
          </h1>
          <p className="text-lg text-muted-foreground leading-relaxed">
            SeafoodVision is a professional visual content library dedicated exclusively to verified real photographs of seafood products. Every image is scientifically named, professionally documented, and traceable to its origin.
          </p>
        </div>

        {/* Mission */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 mb-16">
          <div>
            <h2 className="text-2xl font-bold text-foreground mb-4">Our mission</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The global seafood industry lacks a reliable, standardized visual reference. Product photos are inconsistent, mislabeled, or generated by AI — creating confusion in trade, marketing, and research.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              SeafoodVision was built to solve this. We document real seafood products with scientific precision: species name, product form, state, packaging, and origin — all verified and traceable.
            </p>
          </div>
          <div className="grid grid-cols-2 gap-4">
            {[
              { icon: Camera, title: 'Real photographs only', desc: 'No AI-generated content. Every image is a real photograph of a real product.' },
              { icon: Fish, title: 'Scientific naming', desc: 'Every species is identified by its scientific name and biological family.' },
              { icon: ShieldCheck, title: 'Verified content', desc: 'Assets go through a review process before being published.' },
              { icon: Globe2, title: 'Global coverage', desc: 'Species and products from fishing areas worldwide.' },
            ]?.map((item) => {
              const Icon = item?.icon;
              return (
                <div key={item?.title} className="bg-card rounded-xl border border-border p-4">
                  <div className="w-9 h-9 rounded-xl bg-secondary/10 flex items-center justify-center mb-3">
                    <Icon size={16} className="text-secondary" />
                  </div>
                  <h3 className="font-semibold text-foreground text-sm mb-1">{item?.title}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">{item?.desc}</p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Platform architecture */}
        <div className="bg-card rounded-2xl border border-border p-8 mb-12">
          <h2 className="text-xl font-bold text-foreground mb-6">Platform architecture</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              { label: 'Codex', desc: 'Internal pipeline for image analysis, classification, metadata preparation and quality validation.' },
              { label: 'SeafoodVision', desc: 'Public platform for catalog browsing, licensing, account management and professional access.' },
              { label: 'Knowledge Engine', desc: 'Structured knowledge base linking species, products, and scientific references. Coming soon.' },
            ]?.map((item) => (
              <div key={item?.label}>
                <h3 className="font-semibold text-foreground mb-2">{item?.label}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{item?.desc}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="flex flex-wrap gap-4">
          <Link href="/library" className="btn-primary">Browse the catalog</Link>
          <Link href="/contact" className="btn-outline">Contact us</Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}
